name: all_fam_141
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.15
  webview_flutter: ^4.4.2
  smooth_page_indicator: ^1.1.0
  in_app_review: ^2.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pie_chart: ^5.4.0
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  apphud: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  build_runner: ^2.2.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf